import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Source_Serif_4 } from "next/font/google";
import { Inter } from "next/font/google";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin"],
  weight: ["400", "600", "700"], // adjust as needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       
      >
        {/* <Navbar /> */}
       
         
      
        {children}
       
      </body>
    </html>
  );
}
